### ISSUE TITLE
Attacking mobs causes a crash

### ISSUE THREAD

**Issue by Hath-a-way** [Fyustorm/mInetiface#17]
Attacking any living entity causes the game to crash, even when Attack is disabled in the config. 

All other features work perfectly. 

I'm only running Fabric and this mod. Minecraft version 1.20.6. On Arch Linux.

**Comment by Fyustorm** [comment]
hi I will look tonight

**Comment by Fyustorm** [comment]
Minecraft 1.20.5 is a breaking version (https://fabricmc.net/2024/04/19/1205.html). I don't know why but for now it won't compile )=

**Comment by Fyustorm** [comment]
Here we go !! You can find the new version  for Fabric here : https://minetiface.fyustorm.ovh/releases

**Comment by Hath-a-way** [comment]
:pensive:

**Comment by Hath-a-way** [comment]
Works now, thank you!
