### ISSUE TITLE
zip END header not found error

### ISSUE THREAD

**Issue by 99Squared** [Fyustorm/mInetiface#18]
ive tried probably 10 times i keep getting a zip END header not found error and it wont launch. this only happens when i run it on my debian 10 server pc, it launches just fine on my macbook but when i put in on my server it wont run no matter what. ive tried reinstalling every portion of it. no luck. its the only mod im using. ive tried both forge and fabric same issue. please help.

**Comment by Fyustorm** [comment]
hi the mod should be installed on your client not the server
