### ISSUE TITLE
Crash on Damage

### ISSUE THREAD

**Issue by Flaming9** [Fyustorm/mInetiface#19]
Every time I hit a mob, it closes my game and gives me this error:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.class_2960.<init>(java.lang.String)'

I have tried with a device connected and not connected and it still crashes.

This is my mod list, when i remove Minetiface i can damage mobs with no issue but with it in it crashes. I am using "fabric-loader-0.15.11-1.21"
![Screenshot 2024-08-01 105927](https://github.com/user-attachments/assets/034caf83-4b7d-484b-91a0-9598ac1c9dcc)

Crash report:
[crash-2024-08-01_11.14.17-client.txt](https://github.com/user-attachments/files/16454574/crash-2024-08-01_11.14.17-client.txt)

I hope this is all the information needed, if not please ask and i will provide the necessary info if i can.

**Comment by Fyustorm** [comment]
Hi, the mod is not compatible with Minecraft 1.21 for now I will need to make a new version. I will try to see next week what I can do

**Comment by Fyustorm** [comment]
New version for fabric 1.21 : https://github.com/Fyustorm/mInetiface/releases/tag/v1.21_2.1.0
