### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by rawpie2** [Fyustorm/mInetiface#6]
hello, can you please support minecraft forge 1.18.2, thank you!

**Comment by Fyustorm** [comment]
I was checking the feasibility. I now know it's possible so I will try my best to do it in 2 weeks but no promise

**Comment by Fyustorm** [comment]
Hey you can check the new release here : https://github.com/Fyustorm/mInetiface/releases/tag/v1.18.2-2.0.0
I removed the config menu from the mod but you can still tweak it as you like directly by editing the config file. I updated the [README](https://github.com/Fyustorm/mInetiface/) for more informations.

Please let me know if it's working or not

**Comment by seurimas** [comment]
Your MOD_ID must match your mods.toml value ("minetiface"), or else it will crash on startup.

**Comment by Fyustorm** [comment]
Yep IntelliJ renamed automatically the modid for no reason when I changed the assets path just before releasing ...
Should be fixed !
