### ISSUE TITLE
1.20 Base

### ISSUE THREAD

**Issue by SSeinaru** [Fyustorm/mInetiface#7]
Heyo can you make this for 1.20 base aswell?

**Comment by Fyustorm** [comment]
Hey, what do you mean by 1.20 base ? 1.20.1 is different than 1.20 ?

**Comment by SSeinaru** [comment]
Im sorry i said it confusing. I mean just normal 1.20 not 1.20.1 because when i attempt to play fabric 1.20 with 1.20.1 mod shit crashes

**Comment by Fyustorm** [comment]
That was just the fabric.mod.json that was set to be compatible only with Minecraft 1.20.1 but it also work with Minecraft 1.20. Either edit the file yourself in the minetiface JAR file or you can download this file
[minetiface-1.1.0-1.20.zip](https://github.com/Fyustorm/mInetiface/files/11931132/minetiface-1.1.0-1.20.zip)
and just rename it to a .jar file  (I can't upload .jar files)
